/* Named-boss personalities, story lines, collection titles. Offline data only. */
const BOSS_THEMES = {
  "다낚아": {
    title: "그물 천재 낚시꾼",
    art: "boss_dana",
    minionArt: "minion_dana",
    bullet: "#7ec8ff",
    filter: "hue-rotate(190deg) saturate(1.2)",
    intro: [
      "헤헤, 오늘 씨알이 굵다.",
      "그물만 던지면 다 걸려. 나는 천재거든.",
    ],
    taunts: [
      "미끼 물었지?",
      "생각 그만하고 그냥 걸려.",
      "이 손맛, 프로급이지.",
      "다 낚아. 진짜 다.",
    ],
    warn: "밑밥이 충분해. 이제 본 게임.",
    enter: "큰 거 온다! 내 그물이야!",
    defeat: "……줄이 끊어졌잖아. 다음에 진짜 다 낚아.",
    minion: "미끼 소대",
  },
  "오른손": {
    title: "파괴의 포핸드",
    art: "boss_right",
    minionArt: "minion_right",
    bullet: "#d8ff4a",
    filter: "hue-rotate(70deg) saturate(1.4) brightness(1.1)",
    intro: [
      "코트는 이미 내 쪽이다.",
      "오른손 한 번이면 끝이야.",
    ],
    taunts: [
      "에이스.",
      "받아 봐. 스매시.",
      "라인 안이다.",
      "파괴적으로 간다.",
    ],
    warn: "세컨드 서브는 없다.",
    enter: "게임 포인트. 오른손.",
    defeat: "아웃인가. 다음 세트에서 깨진다.",
    minion: "볼보이",
  },
  "박엄살": {
    title: "조신한 암살자",
    art: "boss_park",
    minionArt: "minion_park",
    bullet: "#ffd0ea",
    filter: "hue-rotate(300deg) saturate(0.85) brightness(1.15)",
    intro: [
      "먼저 인사드릴게요. 오늘도 조심히.",
      "너무 크게 소리 내지 마세요.",
    ],
    taunts: [
      "실례합니다.",
      "아직 예의를 지키는 중이에요.",
      "곧, 다른 얼굴이 나와요.",
      "……조용히 끝낼게요.",
    ],
    warn: "가면을 벗어도 될까요.",
    enter: "조신은 여기까지. 암살 시작.",
    defeat: "들켰네요. 다음엔 인사도 생략할게요.",
    minion: "침묵의 수행원",
  },
  "앞으로빵빵": {
    title: "키 큰 마라토너",
    art: "boss_bang",
    minionArt: "minion_bang",
    bullet: "#ff9a4a",
    filter: "hue-rotate(20deg) saturate(1.3)",
    intro: [
      "코스는 하나다. 앞으로.",
      "숨 차지 마. 나는 아직 워밍업이야.",
    ],
    taunts: [
      "앞으로 달려!",
      "페이스 올려!",
      "아직 반환점도 아니야.",
      "뒤돌아보면 져.",
    ],
    warn: "마지막 스퍼트 들어간다.",
    enter: "앞으로빵빵. 골인까지 직진이다.",
    defeat: "기록은… 다음에 갱신하지.",
    minion: "운동화 함대",
  },
  "남사기관": {
    title: "변화구 마술사",
    art: "boss_namsa",
    minionArt: "minion_namsa",
    bullet: "#ffffff",
    filter: "saturate(0.6) brightness(1.2)",
    intro: [
      "오늘 구위, 마술 수준이다.",
      "직구인 척 커브 던진다.",
    ],
    taunts: [
      "받아봐, 직구.",
      "커브다. 속았지.",
      "체인지업. 타이밍 버렸지.",
      "이 구종, 규칙집에도 없지.",
    ],
    warn: "9회말, 투수 등판.",
    enter: "남사기관. 오늘 완봉한다.",
    defeat: "홈런 맞았네. 다음엔 신구종이다.",
    minion: "야수진",
  },
  "앙큼기사": {
    title: "앙큼 골퍼",
    art: "boss_golf",
    minionArt: "minion_golf",
    bullet: "#f4f0e0",
    filter: "hue-rotate(90deg) saturate(0.7) brightness(1.15)",
    intro: [
      "스마일하면 버디가 들어와.",
      "공 하나만으로도 충분해.",
    ],
    taunts: [
      "드라이버 갈게~",
      "홀인원 각인데?",
      "벙커에 빠뜨려 줄까.",
      "앙큼하지?",
    ],
    warn: "티샷 준비됐지.",
    enter: "앙큼기사, 오늘 라운드 시작.",
    defeat: "보기다. 다음 홀에서 보자.",
    minion: "캐디",
  },
  "빠뜨렀슈": {
    title: "OB 애호가",
    art: "boss_beer",
    minionArt: "minion_beer",
    bullet: "#ffcc55",
    filter: "hue-rotate(45deg) saturate(1.2) brightness(1.05)",
    intro: [
      "한 캔 따고 시작하지.",
      "OB는 공격이고 방어야.",
    ],
    taunts: [
      "들이켜.",
      "거품이 예술이지.",
      "취했다고? 아직 서비스야.",
      "빠뜨렸슈~ 한 캔 더.",
    ],
    warn: "얼은 거 아니다. 차가운 거야.",
    enter: "빠뜨렀슈 등장. 따라 마셔.",
    defeat: "캔이 떨어졌을 뿐. 편의점 들렀다 온다.",
    minion: "따라 마시는 조수",
  },
  "깨발랄지나아C": {
    title: "아이씨 소녀",
    art: "boss_jina",
    minionArt: "minion_jina",
    bullet: "#ff7ab8",
    filter: "hue-rotate(320deg) saturate(1.4)",
    intro: [
      "아이씨, 왜 벌써 왔어.",
      "한복 구겨지잖아. 아이씨!",
    ],
    taunts: [
      "아이씨!",
      "비켜 아이씨.",
      "개구쟁인 거 알아. 아이씨.",
      "귀엽다고 방심하지 마.",
    ],
    warn: "아이씨, 이제 진짜야.",
    enter: "깨발랄지나아C! 아이씨 아이씨!",
    defeat: "아이씨…… 다음엔 안 져.",
    minion: "개구쟁이 무리",
  },
  "우정신프로": {
    title: "칭찬 공주",
    art: "boss_woo",
    minionArt: "minion_woo",
    bullet: "#ff9ad4",
    filter: "hue-rotate(310deg) saturate(0.9) brightness(1.2)",
    intro: [
      "오늘은 네가 주인공이야.",
      "잘하고 있어. 정말.",
    ],
    taunts: [
      "잘한다 잘한다~",
      "그 회피, 교과서다.",
      "칭찬은 칼보다 빨라.",
      "칭찬이 과하면 어지러워지지~",
    ],
    warn: "이제 본격 칭찬 들어갈게.",
    enter: "우정신프로. 칭찬 세례 시작.",
    defeat: "그래도 오늘 진짜 멋있었어. 인정.",
    minion: "응원단",
  },
  "빌런": {
    title: "백발의 연출가",
    art: "boss_villain",
    minionArt: "minion_villain",
    bullet: "#d8dee8",
    filter: "saturate(0.55) brightness(1.12)",
    intro: [
      "악역은 날씬해야 티가 나지.",
      "각본은 이미 내가 썼다.",
    ],
    taunts: [
      "거기, 예측 가능하네.",
      "박수 타이밍을 알려줄게.",
      "침묵이 제일 시끄러워.",
      "내 큐 사인만 보면 돼.",
    ],
    warn: "2막이다. 조명 내려.",
    enter: "빌런. 무대는 내가 가져간다.",
    defeat: "커튼콜은… 다음에.",
    minion: "흑막 스태프",
  },
  "골프보다구찌": {
    title: "그린 위의 구찌왕",
    art: "boss_gucci",
    minionArt: "minion_gucci",
    bullet: "#7edc8a",
    filter: "hue-rotate(95deg) saturate(1.15) brightness(1.08)",
    intro: [
      "스윙할 때 말 거는 게 내 루틴이야.",
      "클럽보다 한마디가 더 세다.",
    ],
    taunts: [
      "어허, 지금 백스윙이야?",
      "나이스~ 아니 방금 거.",
      "기침은 매너 아냐?",
      "구찌 한 방이면 보기다.",
    ],
    warn: "티샷 때 내가 한마디 한다.",
    enter: "골프보다구찌. 말은 규정에 없어.",
    defeat: "오늘은 내가 먼저 흔들렸군.",
    minion: "기침 캐디",
  },
  "버디요정": {
    title: "회전의 요정",
    art: "boss_buddy",
    minionArt: "minion_buddy",
    bullet: "#b8ffd4",
    filter: "hue-rotate(130deg) saturate(1.1) brightness(1.1)",
    intro: [
      "부드럽게, 그러나 멈추지 않아.",
      "스핀이 도는 만큼 탄도 돌아.",
    ],
    taunts: [
      "빙글~",
      "한 바퀴 더.",
      "요정도 운동해.",
      "회전은 예절이야.",
    ],
    warn: "회전이 빨라진다.",
    enter: "버디요정. 한 바퀴 돌아가 볼까.",
    defeat: "어지러워. 그래도 우아했지.",
    minion: "요정 가루",
  },
  "기라성": {
    title: "젊음이 무기",
    art: "boss_gira",
    minionArt: "minion_gira",
    bullet: "#ff66dd",
    filter: "hue-rotate(310deg) saturate(1.4)",
    intro: [
      "나이로 덤비지 마. 나는 젊어.",
      "경험? 그게 나보다 빨라?",
    ],
    taunts: [
      "나는 젊으니까 다 이겨.",
      "청춘 스탯 봐.",
      "워밍업? 이미 끝났어.",
      "내일의 나는 더 어려.",
    ],
    warn: "젊은 피가 끓는다.",
    enter: "기라성. 젊음으로 밀어붙인다.",
    defeat: "잠깐 낮잠… 아직 젊은데.",
    minion: "청춘 사단",
  },
  "김탁구": {
    title: "얍실 탁구왕",
    art: "boss_takgu",
    minionArt: "minion_takgu",
    bullet: "#ff5a5a",
    filter: "hue-rotate(0deg) saturate(1.2)",
    intro: [
      "얍실한 탁구가 내 적성이야.",
      "두부과자 먹고 서브 넣는다.",
    ],
    taunts: [
      "어느 방향으로 미사일 보낼까.",
      "읽혔다고? 그게 함정이지.",
      "숏, 롱, 옆. 얍실하게 해주마.",
      "탁구채가 도면보다 빨라.",
    ],
    warn: "듀스다. 얍실 모드.",
    enter: "김탁구. 서브는 몰래 넣는다.",
    defeat: "과자 떨어뜨렸다… 재경기!",
    minion: "탁구채 군단",
  },
};
