/* Offline roster — unique kits, lines, sprite sheets. */
const CHAR_NAMES = [
  "다낚아", "오른손", "박엄살", "앞으로빵빵", "남사기관", "앙큼기사",
  "빠뜨렀슈", "깨발랄지나아C", "우정신프로", "빌런", "골프보다구찌", "버디요정",
  "기라성", "김탁구", "커피 친구",
];

const SHEET_COLS = 4;
const SHEET_ROWS = 4;
const FR = {
  idle: 0, move: 1, punch: 2, kick: 3,
  punchUp: 4, kickUp: 5, punchDown: 6, kickDown: 7,
  punchSide: 8, kickSide: 9, special: 10, hurt: 11,
  fly: 12, win: 13, ko: 14, special2: 15,
};

const CHARS = {
  "다낚아": {
    title: "그물 천재 낚시꾼",
    art: "boss_dana",
    sheet: "sheet_dana",
    color: "#7ec8ff",
    accent: "#1a6aa8",
    hp: 360,
    speed: 1.02,
    aggro: 0.5,
    punch: { name: "미끼탄", type: "shot", dmg: 6, startup: 0.08, recover: 0.22, speed: 340, r: 11, shots: 1, color: "#7ec8ff", shape: "lure", linger: 1.1 },
    kick: { name: "그물채", type: "melee", dmg: 9, startup: 0.1, recover: 0.28, range: 150, arc: 1.1, color: "#7ec8ff", shape: "net" },
    special: { name: "다 낚아 그물", type: "grab", dmg: 16, startup: 0.12, recover: 0.4, range: 210, color: "#7ec8ff", shape: "net" },
    intro: ["헤헤, 오늘 씨알이 굵다.", "그물만 던지면 다 걸려. 나는 천재거든."],
    pickMe: ["나로 해! 씨알이 굵다.", "그물 천재 안 고를 거야?", "이 손맛, 골라봐."],
    taunts: ["미끼 물었지?", "생각 그만하고 그냥 걸려.", "이 손맛, 프로급이지.", "다 낚아. 진짜 다."],
    atk: ["걸려!", "손맛이다!", "그물 간다!"],
    hurt: ["줄이…", "빠져나갔네.", "아직 안 잡혔어."],
    win: "오늘 월척. 스트레스도 같이 낚았다.",
    defeat: "……줄이 끊어졌잖아. 다음에 진짜 다 낚아.",
  },
  "오른손": {
    title: "파괴의 포핸드",
    art: "boss_right",
    sheet: "sheet_right",
    color: "#d8ff4a",
    accent: "#6a8a10",
    hp: 350,
    speed: 1.08,
    aggro: 0.68,
    punch: { name: "포핸드", type: "shot", dmg: 7, startup: 0.07, recover: 0.2, speed: 520, r: 12, shots: 1, color: "#d8ff4a", shape: "ball" },
    kick: { name: "스매시", type: "melee", dmg: 11, startup: 0.12, recover: 0.3, range: 130, smash: 1, color: "#d8ff4a", shape: "smash" },
    special: { name: "파괴 에이스", type: "shot", dmg: 18, startup: 0.14, recover: 0.42, speed: 640, r: 18, shots: 1, color: "#e8ff88", shape: "ball" },
    intro: ["코트는 이미 내 쪽이다.", "오른손 한 번이면 끝이야."],
    pickMe: ["오른손 한 번이면 끝이야.", "나로 해. 에이스다.", "코트는 이미 내 쪽이다."],
    taunts: ["에이스.", "받아 봐. 스매시.", "라인 안이다.", "파괴적으로 간다."],
    atk: ["받아!", "스매시!", "에이스다!"],
    hurt: ["아웃…?", "폴트는 아니야.", "세컨드다."],
    win: "게임, 세트, 매치. 시원하다.",
    defeat: "아웃인가. 다음 세트에서 깨진다.",
  },
  "박엄살": {
    title: "조신한 암살자",
    art: "boss_park",
    sheet: "sheet_park",
    color: "#ffd0ea",
    accent: "#a05080",
    hp: 300,
    speed: 1.22,
    aggro: 0.4,
    punch: { name: "인사칼", type: "melee", dmg: 6, startup: 0.05, recover: 0.14, range: 88, color: "#ffd0ea", shape: "stab" },
    kick: { name: "예절참", type: "dash", dmg: 10, startup: 0.08, recover: 0.26, speed: 620, color: "#ffd0ea", shape: "slash" },
    special: { name: "가면 벗기", type: "blink", dmg: 17, startup: 0.1, recover: 0.36, color: "#ffd0ea", shape: "slash" },
    intro: ["먼저 인사드릴게요. 오늘도 조심히.", "너무 크게 소리 내지 마세요."],
    pickMe: ["실례지만… 저로 하시겠어요?", "조용히, 잘 부탁드려요.", "골라주시면 예의를 지키죠."],
    taunts: ["실례합니다.", "아직 예의를 지키는 중이에요.", "곧, 다른 얼굴이 나와요.", "……조용히 끝낼게요."],
    atk: ["실례.", "조용히.", "가면 벗어요."],
    hurt: ["들켰나요.", "아직 조신한데요.", "가면이…"],
    win: "인사까지 마쳤으니, 이만.",
    defeat: "들켰네요. 다음엔 인사도 생략할게요.",
  },
  "앞으로빵빵": {
    title: "키 큰 마라토너",
    art: "boss_bang",
    sheet: "sheet_bang",
    color: "#ff9a4a",
    accent: "#c05010",
    hp: 370,
    speed: 1.32,
    aggro: 0.82,
    punch: { name: "스퍼트주먹", type: "dash", dmg: 7, startup: 0.06, recover: 0.2, speed: 540, color: "#ff9a4a", shape: "fist" },
    kick: { name: "반환점킥", type: "dash", dmg: 10, startup: 0.1, recover: 0.28, speed: 700, color: "#ff9a4a", shape: "kick" },
    special: { name: "골인 직진", type: "dash", dmg: 16, startup: 0.12, recover: 0.4, speed: 920, pierce: 1, color: "#ff9a4a", shape: "rush" },
    intro: ["코스는 하나다. 앞으로.", "숨 차지 마. 나는 아직 워밍업이야."],
    pickMe: ["앞으로! 나로 달려.", "워밍업은 이미 끝났어.", "뒤돌아보면 져. 골라."],
    taunts: ["앞으로 달려!", "페이스 올려!", "아직 반환점도 아니야.", "뒤돌아보면 져."],
    atk: ["앞으로!", "빵빵!", "스퍼트!"],
    hurt: ["페이스가…", "아직 괜찮아.", "반환점이야."],
    win: "골인. 기록이 스트레스다.",
    defeat: "기록은… 다음에 갱신하지.",
  },
  "남사기관": {
    title: "변화구 마술사",
    art: "boss_namsa",
    sheet: "sheet_namsa",
    color: "#f4f7ff",
    accent: "#4a6080",
    hp: 340,
    speed: 1.0,
    aggro: 0.48,
    punch: { name: "직구", type: "shot", dmg: 7, startup: 0.07, recover: 0.2, speed: 560, r: 11, shots: 1, color: "#ffffff", shape: "ball" },
    kick: { name: "커브", type: "shot", dmg: 8, startup: 0.1, recover: 0.26, speed: 400, r: 12, shots: 1, curve: 1.4, color: "#c8e0ff", shape: "ball" },
    special: { name: "마술 체인지업", type: "shot", dmg: 7, startup: 0.12, recover: 0.4, speed: 380, r: 12, shots: 3, curve: 1.6, color: "#ffffff", shape: "ball" },
    intro: ["오늘 구위, 마술 수준이다.", "직구인 척 커브 던진다."],
    pickMe: ["나로 해. 오늘 완봉한다.", "직구인 척 커브 던진다.", "이 구종, 나만 있어."],
    taunts: ["받아봐, 직구.", "커브다. 속았지.", "체인지업. 타이밍 버렸지.", "이 구종, 규칙집에도 없지."],
    atk: ["직구!", "커브!", "속았지!"],
    hurt: ["홈런인가.", "볼이네.", "사인 미스."],
    win: "완봉승. 마술은 끝나지 않아.",
    defeat: "홈런 맞았네. 다음엔 신구종이다.",
  },
  "앙큼기사": {
    title: "앙큼 골퍼",
    art: "boss_golf",
    sheet: "sheet_golf",
    color: "#f4c0e0",
    accent: "#905070",
    hp: 330,
    speed: 0.98,
    aggro: 0.45,
    punch: { name: "클럽콕", type: "melee", dmg: 7, startup: 0.09, recover: 0.22, range: 160, color: "#f4c0e0", shape: "club" },
    kick: { name: "벙커킥", type: "spray", dmg: 5, startup: 0.1, recover: 0.3, shots: 5, speed: 300, r: 8, color: "#e8d0a0", shape: "sand" },
    special: { name: "홀인원 드라이브", type: "shot", dmg: 17, startup: 0.16, recover: 0.44, speed: 500, r: 18, shots: 1, color: "#f4f0e0", shape: "ball" },
    intro: ["스마일하면 버디가 들어와.", "공 하나만으로도 충분해."],
    pickMe: ["나로 하면 버디야~", "앙큼하지? 골라봐.", "홀인원 각인데?"],
    taunts: ["드라이버 갈게~", "홀인원 각인데?", "벙커에 빠뜨려 줄까.", "앙큼하지?"],
    atk: ["홀인원!", "드라이버!", "앙큼~"],
    hurt: ["보기야.", "러프네.", "오비는 아니야."],
    win: "버디. 스마일 유지.",
    defeat: "보기다. 다음 홀에서 보자.",
  },
  "빠뜨렀슈": {
    title: "OB 애호가",
    art: "boss_beer",
    sheet: "sheet_beer",
    color: "#ffcc55",
    accent: "#b07010",
    hp: 400,
    speed: 0.84,
    aggro: 0.5,
    scale: 0.78,
    punch: { name: "캔뚜껑", type: "shot", dmg: 8, startup: 0.1, recover: 0.26, speed: 320, r: 14, shots: 1, arc: 220, color: "#ffcc55", shape: "can" },
    kick: { name: "거품발", type: "spray", dmg: 6, startup: 0.12, recover: 0.32, shots: 4, speed: 240, r: 13, slow: 0.45, color: "#ffe9a0", shape: "foam" },
    special: { name: "들이켜 스플래시", type: "burst", dmg: 14, startup: 0.14, recover: 0.46, range: 170, slow: 0.5, color: "#ffcc55", shape: "foam" },
    intro: ["한 캔 따고 시작하지.", "OB는 공격이고 방어야."],
    pickMe: ["나로 해. 한 캔 따고 시작하지.", "서비스야, 골라.", "빠뜨렀슈~ 나로 한 캔."],
    taunts: ["들이켜.", "거품이 예술이지.", "취했다고? 아직 서비스야.", "빠뜨렸슈~ 한 캔 더."],
    atk: ["들이켜!", "한 캔 더!", "빠뜨렀슈~"],
    hurt: ["거품이 넘쳤…", "아직 안 취했어.", "서비스야."],
    win: "캔이 이겼다. 건배.",
    defeat: "캔이 떨어졌을 뿐. 편의점 들렀다 온다.",
  },
  "깨발랄지나아C": {
    title: "아이씨 소녀",
    art: "boss_jina",
    sheet: "sheet_jina",
    color: "#ff7ab8",
    accent: "#c02070",
    hp: 300,
    speed: 1.24,
    aggro: 0.78,
    punch: { name: "아이씨손", type: "melee", dmg: 4, startup: 0.04, recover: 0.1, range: 78, hits: 3, color: "#ff7ab8", shape: "slap" },
    kick: { name: "한복발", type: "spin", dmg: 6, startup: 0.08, recover: 0.28, hits: 3, range: 100, color: "#ff7ab8", shape: "spin" },
    special: { name: "아이씨 난타", type: "spin", dmg: 5, startup: 0.08, recover: 0.4, hits: 6, range: 120, color: "#ff7ab8", shape: "spin" },
    intro: ["아이씨, 왜 벌써 왔어.", "한복 구겨지잖아. 아이씨!"],
    pickMe: ["아이씨, 왜 안 골라.", "나로 해 아이씨!", "귀엽다고 다른 애 고르지 마."],
    taunts: ["아이씨!", "비켜 아이씨.", "개구쟁인 거 알아. 아이씨.", "귀엽다고 방심하지 마."],
    atk: ["아이씨!", "비켜!", "개구쟁이!"],
    hurt: ["아이씨…", "한복이!", "진짜 아이씨."],
    win: "아이씨, 내가 이겼잖아.",
    defeat: "아이씨…… 다음엔 안 져.",
  },
  "우정신프로": {
    title: "칭찬 공주",
    art: "boss_woo",
    sheet: "sheet_woo",
    color: "#ff9ad4",
    accent: "#d060a0",
    hp: 320,
    speed: 1.04,
    aggro: 0.42,
    punch: { name: "칭찬손", type: "shot", dmg: 5, startup: 0.08, recover: 0.22, speed: 300, r: 13, shots: 1, home: 0.08, color: "#ff9ad4", shape: "heart" },
    kick: { name: "하트킥", type: "melee", dmg: 8, startup: 0.1, recover: 0.26, range: 110, stun: 0.2, color: "#ff9ad4", shape: "heart" },
    special: { name: "칭찬 세례", type: "shot", dmg: 5, startup: 0.12, recover: 0.42, speed: 280, r: 12, shots: 5, home: 0.12, stun: 0.28, color: "#ff9ad4", shape: "heart" },
    intro: ["오늘은 네가 주인공이야.", "잘하고 있어. 정말."],
    pickMe: ["나를 고르면 네가 주인공이야.", "잘 골랐어. 아직 안 골랐지만.", "칭찬은 골라주는 것부터~"],
    taunts: ["잘한다 잘한다~", "그 회피, 교과서다.", "칭찬은 칼보다 빨라.", "칭찬이 과하면 어지러워지지~"],
    atk: ["잘한다~", "최고야!", "칭찬!"],
    hurt: ["그래도 멋져.", "괜찮아~", "잘 맞고 있어."],
    win: "오늘 진짜 멋있었어. 내가 이겼지만.",
    defeat: "그래도 오늘 진짜 멋있었어. 인정.",
  },
  "빌런": {
    title: "백발의 연출가",
    art: "boss_villain",
    sheet: "sheet_villain",
    color: "#d8dee8",
    accent: "#606878",
    hp: 350,
    speed: 0.96,
    aggro: 0.46,
    punch: { name: "큐사인", type: "melee", dmg: 7, startup: 0.09, recover: 0.22, range: 120, color: "#d8dee8", shape: "baton" },
    kick: { name: "커튼콜", type: "melee", dmg: 10, startup: 0.12, recover: 0.3, range: 140, color: "#d8dee8", shape: "slash" },
    special: { name: "2막 조명", type: "burst", dmg: 12, startup: 0.14, recover: 0.44, range: 180, stun: 0.5, color: "#f0f4ff", shape: "spot" },
    intro: ["악역은 날씬해야 티가 나지.", "각본은 이미 내가 썼다."],
    pickMe: ["각본상 주인공은 나다.", "큐 사인만 보면 돼. 나를.", "악역을 고르는 센스, 있지?"],
    taunts: ["거기, 예측 가능하네.", "박수 타이밍을 알려줄게.", "침묵이 제일 시끄러워.", "내 큐 사인만 보면 돼."],
    atk: ["큐!", "2막!", "조명 내려!"],
    hurt: ["애드리브인가.", "각본에 없는데.", "리허설이야."],
    win: "커튼콜은 내 거야.",
    defeat: "커튼콜은… 다음에.",
  },
  "골프보다구찌": {
    title: "그린 위의 구찌왕",
    art: "boss_gucci",
    sheet: "sheet_gucci",
    color: "#7edc8a",
    accent: "#2a8a40",
    hp: 340,
    speed: 1.0,
    aggro: 0.58,
    punch: { name: "구찌콕", type: "shot", dmg: 6, startup: 0.07, recover: 0.2, speed: 480, r: 10, shots: 1, stun: 0.16, color: "#7edc8a", shape: "word" },
    kick: { name: "백스윙킥", type: "melee", dmg: 9, startup: 0.11, recover: 0.28, range: 130, color: "#7edc8a", shape: "club" },
    special: { name: "기침 방해", type: "shot", dmg: 7, startup: 0.1, recover: 0.38, speed: 420, r: 12, shots: 3, stun: 0.22, color: "#b8f0c0", shape: "word" },
    intro: ["스윙할 때 말 거는 게 내 루틴이야.", "클럽보다 한마디가 더 세다."],
    pickMe: ["어허, 지금 누구 고르는 거야?", "구찌 한 방이면 보기다. 나로 해.", "나이스~ 나를 고르는 거."],
    taunts: ["어허, 지금 백스윙이야?", "나이스~ 아니 방금 거.", "기침은 매너 아냐?", "구찌 한 방이면 보기다."],
    atk: ["어허!", "구찌!", "나이스~?"],
    hurt: ["말 좀 그만…", "집중이…", "매너 게임이야."],
    win: "말은 규정에 없고, 승리는 내 거야.",
    defeat: "오늘은 내가 먼저 흔들렸군.",
  },
  "버디요정": {
    title: "회전의 요정",
    art: "boss_buddy",
    sheet: "sheet_buddy",
    color: "#b8ffd4",
    accent: "#30a070",
    hp: 290,
    speed: 1.18,
    aggro: 0.52,
    punch: { name: "요정손", type: "orbit", dmg: 6, startup: 0.08, recover: 0.24, shots: 2, color: "#b8ffd4", shape: "star" },
    kick: { name: "스핀킥", type: "spin", dmg: 7, startup: 0.08, recover: 0.26, hits: 3, range: 110, color: "#b8ffd4", shape: "spin" },
    special: { name: "한 바퀴 더", type: "orbit", dmg: 6, startup: 0.1, recover: 0.4, shots: 5, color: "#d8ffe8", shape: "star" },
    intro: ["부드럽게, 그러나 멈추지 않아.", "스핀이 도는 만큼 탄도 돌아."],
    pickMe: ["빙글~ 나로 한 바퀴.", "요정도 출전하고 싶어.", "골라주면 우아하게 이겨줄게."],
    taunts: ["빙글~", "한 바퀴 더.", "요정도 운동해.", "회전은 예절이야."],
    atk: ["빙글~", "돌아!", "요정!"],
    hurt: ["어지러워.", "스핀이 깨졌어.", "우아하게…"],
    win: "회전은 예절, 승리는 버디.",
    defeat: "어지러워. 그래도 우아했지.",
  },
  "기라성": {
    title: "젊음이 무기",
    art: "boss_gira",
    sheet: "sheet_gira",
    color: "#ff66dd",
    accent: "#c02090",
    hp: 310,
    speed: 1.26,
    aggro: 0.8,
    punch: { name: "청춘펀치", type: "melee", dmg: 6, startup: 0.05, recover: 0.14, range: 90, hits: 2, color: "#ff66dd", shape: "fist" },
    kick: { name: "내일킥", type: "dash", dmg: 9, startup: 0.08, recover: 0.24, speed: 680, color: "#ff66dd", shape: "kick" },
    special: { name: "젊음 러시", type: "dash", dmg: 14, startup: 0.1, recover: 0.36, speed: 860, pierce: 1, color: "#ff66dd", shape: "rush" },
    intro: ["나이로 덤비지 마. 나는 젊어.", "경험? 그게 나보다 빨라?"],
    pickMe: ["젊으니까 나로 해.", "청춘 스탯 봐. 골라.", "내일의 나는 더 어려. 오늘은 나."],
    taunts: ["나는 젊으니까 다 이겨.", "청춘 스탯 봐.", "워밍업? 이미 끝났어.", "내일의 나는 더 어려."],
    atk: ["젊음!", "청춘!", "더 빨라!"],
    hurt: ["잠깐 낮잠…", "아직 젊은데.", "스탯 봐."],
    win: "젊음이 이겼다. 내일도 어려.",
    defeat: "잠깐 낮잠… 아직 젊은데.",
  },
  "김탁구": {
    title: "얍실 탁구왕",
    art: "boss_takgu",
    sheet: "sheet_takgu",
    color: "#ff5a5a",
    accent: "#a01818",
    hp: 380,
    speed: 0.92,
    aggro: 0.62,
    punch: { name: "숏서브", type: "shot", dmg: 6, startup: 0.05, recover: 0.16, speed: 620, r: 8, shots: 1, color: "#ff5a5a", shape: "ball" },
    kick: { name: "롱드라이브", type: "shot", dmg: 9, startup: 0.1, recover: 0.26, speed: 480, r: 11, shots: 1, bounce: 2, color: "#ff8866", shape: "ball" },
    special: { name: "얍실 미사일", type: "shot", dmg: 7, startup: 0.1, recover: 0.4, speed: 500, r: 10, shots: 3, bounce: 3, color: "#ff5a5a", shape: "ball" },
    intro: ["얍실한 탁구가 내 적성이야.", "두부과자 먹고 서브 넣는다."],
    pickMe: ["얍실하게, 나로 해.", "두부과자 먹고 출전한다.", "나를 고르는 게 정답이지."],
    taunts: ["어느 방향으로 미사일 보낼까.", "읽혔다고? 그게 함정이지.", "숏, 롱, 옆. 얍실하게 해주마.", "탁구채가 도면보다 빨라."],
    atk: ["얍실!", "숏!", "과자!"],
    hurt: ["과자 떨어뜨렸다.", "듀스다.", "재경기?"],
    win: "얍실하게, 그러나 정당하게.",
    defeat: "과자 떨어뜨렸다… 재경기!",
  },
  "커피 친구": {
    title: "봉사 바리스타",
    art: "boss_coffee",
    sheet: "sheet_coffee",
    color: "#c8a070",
    accent: "#6a4a28",
    hp: 340,
    speed: 1.0,
    aggro: 0.5,
    punch: { name: "커피스플래시", type: "spray", dmg: 6, startup: 0.08, recover: 0.22, shots: 4, speed: 360, r: 8, color: "#c89050", shape: "coffee" },
    kick: { name: "주걱킥", type: "melee", dmg: 9, startup: 0.1, recover: 0.26, range: 130, color: "#c8a070", shape: "paddle" },
    special: { name: "따뜻한 한 끼", type: "burst", dmg: 13, startup: 0.12, recover: 0.42, range: 150, heal: 18, color: "#c8a070", shape: "steam" },
    intro: ["커피 한 잔 하고 붙자.", "밥은 내가 했어. 싸움도 내가 할게."],
    pickMe: ["나 골라. 커피 타고 올게.", "밥은 내가 했어. 나도 뽑아줘.", "봉사활동이야, 나로 해."],
    taunts: ["식기 전에 맞아.", "이건 봉사활동이야, 맞아줘.", "카페인 과다야.", "국 한 그릇 더 줄까."],
    atk: ["뜨거워!", "밥 먹어!", "봉사!"],
    hurt: ["커피가 식었네.", "주걱이…", "배고픈가."],
    win: "배부르지? 스트레스도 소화됐다.",
    defeat: "커피가… 식었네. 다음엔 두 잔이야.",
  },
};

function charOf(name) {
  return CHARS[name] || CHARS["커피 친구"];
}

function pickLine(arr) {
  if (!arr || !arr.length) return "";
  return arr[(Math.random() * arr.length) | 0];
}
